//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocumentId { get; set; }
        public int UserId { get; set; }
        public string DocumentType { get; set; }
        public string DocumentTitle { get; set; }
        public Nullable<System.DateTime> GeneratedDate { get; set; }
        public string Status { get; set; }
        public int RelatedEntityId { get; set; }
        public string FilePath { get; set; }
    }
}
