//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonationItem
    {
        public int DonationItemId { get; set; }
        public int DonationId { get; set; }
        public int ItemId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Unit { get; set; }
    
        public virtual InventoryItem InventoryItem { get; set; }
        public virtual DonationItem DonationItems1 { get; set; }
        public virtual DonationItem DonationItem1 { get; set; }
    }
}
